/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "ble_motion_service.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside MOTION SERVICE packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside MOTION SERVICE packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_MOTION_DATA_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Motion Data. */ 

/**@brief Function for encoding Motion Data.
 *
 * @param[in]   p_motion_data              Motion Data characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t motion_data_encode(ble_motion_service_motion_data_t * p_motion_data, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_motion_data->accel, &encoded_buffer[len]); 
    len += bds_uint8_array_encode(&p_motion_data->gyro1, &encoded_buffer[len]); 
    len += bds_uint8_array_encode(&p_motion_data->gyro2, &encoded_buffer[len]); 
    len += bds_uint16_encode(&p_motion_data->counter, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_motion_service       MOTION SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_motion_service_t * p_motion_service, ble_evt_t * p_ble_evt)
{
    p_motion_service->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_motion_service       MOTION SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_motion_service_t * p_motion_service, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_motion_service->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_motion_service       MOTION SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_motion_service_t * p_motion_service, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_motion_service->motion_data_handles.cccd_handle)
    {
        if(p_motion_service->evt_handler != NULL)
        {
            ble_motion_service_evt_t evt;
            evt.evt_type = BLE_MOTION_SERVICE_MOTION_DATA_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_motion_service->evt_handler(p_motion_service, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_motion_service_t * p_motion_service, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_motion_service       MOTION SERVICE Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_motion_service_on_ble_evt(ble_motion_service_t * p_motion_service, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_motion_service, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_motion_service, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_motion_service, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_motion_service, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the MOTION SERVICE. */
uint32_t ble_motion_service_init(ble_motion_service_t * p_motion_service, const ble_motion_service_init_t * p_motion_service_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_motion_service->evt_handler = p_motion_service_init->evt_handler;
    p_motion_service->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x1F, 0x35, 0xBD, 0x4B, 0xAE, 0xD0, 0x68, 0x9C, 0xE2, 0x48, 0x81, 0x1D, 0x00, 0x00, 0x39, 0xDA}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x5D22;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_motion_service->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Motion Data characteristic
    ble_motion_service_motion_data_t motion_data_initial_value = p_motion_service_init->ble_motion_service_motion_data_initial_value; 

    uint8_t motion_data_encoded_value[MAX_MOTION_DATA_LEN];
    ble_add_char_params_t add_motion_data_params;
    memset(&add_motion_data_params, 0, sizeof(add_motion_data_params));
    
    add_motion_data_params.uuid                = 0xC921;
    add_motion_data_params.uuid_type           = ble_uuid.type; 
    add_motion_data_params.max_len             = MAX_MOTION_DATA_LEN;
    add_motion_data_params.init_len            = motion_data_encode(&motion_data_initial_value, motion_data_encoded_value);
    add_motion_data_params.p_init_value        = motion_data_encoded_value; 
    add_motion_data_params.char_props.notify   = 1; 
    add_motion_data_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_motion_data_params.is_var_len          = 1; 

    err_code = characteristic_add(p_motion_service->service_handle, &add_motion_data_params, &(p_motion_service->motion_data_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for sending the Motion Data. */
uint32_t ble_motion_service_motion_data_send(ble_motion_service_t * p_motion_service, ble_motion_service_motion_data_t * p_motion_data)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_motion_service->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_MOTION_DATA_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));
        //encoded_value[0]=0xAA;
        hvx_len           = motion_data_encode(p_motion_data, encoded_value);
        //hvx_len=10;
				hvx_params.handle = p_motion_service->motion_data_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_motion_service->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

