/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_bas.h" 
#include "ble_motion_service.h" 

ble_bas_t    					 m_bas; 
ble_motion_service_t    m_motion_service; 

uint8_t m_motion_service_motion_data_initial_value_accel_arr[6]; 
uint8_t m_motion_service_motion_data_initial_value_gyro1_arr[6]; 
uint8_t m_motion_service_motion_data_initial_value_gyro2_arr[6]; 


/**@brief Function for handling the Battery Service events.
 *
 * @details This function will be called for all Battery Service events which are passed to
 *          the application.
 *
 * @param[in]   p_battery_service   Battery Service structure.
 * @param[in]   p_evt   Event received from the Battery Service.
 */
static void on_bas_evt(ble_bas_t * p_bas, ble_bas_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_BAS_BATTERY_LEVEL_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: BAS_BATTERY_LEVEL evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for handling the MOTION SERVICE events.
 *
 * @details This function will be called for all MOTION SERVICE events which are passed to
 *          the application.
 *
 * @param[in]   p_motion_service   MOTION SERVICE structure.
 * @param[in]   p_evt   Event received from the MOTION SERVICE.
 */
static void on_motion_service_evt(ble_motion_service_t * p_motion_service, ble_motion_service_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_MOTION_SERVICE_MOTION_DATA_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: MOTION_SERVICE_MOTION_DATA evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_MOTION_SERVICE_MOTION_DATA_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: MOTION_SERVICE_MOTION_DATA evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_MOTION_SERVICE_MOTION_DATA_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: MOTION_SERVICE_MOTION_DATA evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_bas_init_t    bas_init; 
    ble_motion_service_init_t    motion_service_init; 
    

    // Initialize Battery Service.
    memset(&bas_init, 0, sizeof(bas_init));

    bas_init.evt_handler = on_bas_evt; 
    bas_init.is_battery_level_notify_supported = true;
    memset(&bas_init.ble_bas_battery_level_initial_value.level,
           0x00,
           sizeof(bas_init.ble_bas_battery_level_initial_value.level));

    err_code = ble_bas_init(&m_bas, &bas_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Initialize MOTION SERVICE.
    memset(&motion_service_init, 0, sizeof(motion_service_init));

    motion_service_init.evt_handler = on_motion_service_evt; 
    motion_service_init.ble_motion_service_motion_data_initial_value.accel.size = 6;
    motion_service_init.ble_motion_service_motion_data_initial_value.accel.p_data = m_motion_service_motion_data_initial_value_accel_arr; 
    motion_service_init.ble_motion_service_motion_data_initial_value.gyro1.size = 6;
    motion_service_init.ble_motion_service_motion_data_initial_value.gyro1.p_data = m_motion_service_motion_data_initial_value_gyro1_arr; 
    motion_service_init.ble_motion_service_motion_data_initial_value.gyro2.size = 6;
    motion_service_init.ble_motion_service_motion_data_initial_value.gyro2.p_data = m_motion_service_motion_data_initial_value_gyro2_arr; 
    memset(&motion_service_init.ble_motion_service_motion_data_initial_value.counter,
           0x00,
           sizeof(motion_service_init.ble_motion_service_motion_data_initial_value.counter));

    err_code = ble_motion_service_init(&m_motion_service, &motion_service_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_bas_on_ble_evt(&m_bas, p_ble_evt); 
    ble_motion_service_on_ble_evt(&m_motion_service, p_ble_evt); 
}
